
public class Ex02_Exception {

	public static void main(String[] args) {
		System.out.println("main start");
		int num = 100;
		int result = 0;
		
		
		//개발자가 의심되면
		try {
			
		} catch (Exception e) {
			
		}
		for(int i = 0 ; i < 10 ; i++) {
			result = num / (int)(Math.random() * 10);	//0~9 난수
			System.out.println("result : " + result + " i : " + i);
		}
		
		System.out.println("main end");

	}

}
